### ISSUE TITLE
Bug with Button Component

### ISSUE THREAD

**Issue by ayushagarwalk** [react-ui-kit/dribbble2react#36]
http://prntscr.com/nsfzpk
Screenshot

im not able to change the button color
its always white, anywhere i use it.

**Comment by mohanyadav** [comment]
1. Start by expanding the components folder and open Button.js
![Button](https://user-images.githubusercontent.com/11350400/58403678-eead1300-8080-11e9-89a4-fd8383a4b7f2.JPG)

2. Add the constants custom, startColorCustom and endColorCustom in the Button.js render() method. We are creating these so that we can pass them as props
![Button2](https://user-images.githubusercontent.com/11350400/58405117-587aec00-8084-11e9-804f-301d3def3ae1.JPG)

3. Scroll below and copy and paste the entire code block of if(gradient) and change the if(gradient) to if(custom). Also change the colors={[startColor, endColor]} to colors={[startColorCustom, endColorCustom]} inside the LinearGradient which is inside TouchableOpacity
![Button3](https://user-images.githubusercontent.com/11350400/58404283-67f93580-8082-11e9-9548-f364df9780ab.JPG)

4. Expand screens folder and open Welcome.js
![Screen](https://user-images.githubusercontent.com/11350400/58404490-d807bb80-8082-11e9-942c-b68a50e5d613.JPG)

5. Now you can create a <Button /> component and pass the colors as props -> startColorCustom and endColorCustom. Don't forget to add the custom prop to the Button component
![CustomButton](https://user-images.githubusercontent.com/11350400/58404655-3cc31600-8083-11e9-9d80-3a89b57df871.JPG)

6. Done! Now you can preview your custom colored Button
![Preview](https://user-images.githubusercontent.com/11350400/58404834-b1965000-8083-11e9-93ed-dc3ebe692d8e.JPG)


@ayushagarwalk

**Comment by hetmann** [comment]
@mohanyadav no need to add a new prop "**custom**", you can use the **gradient** prop with **startColor** & **endColor** with the same functionality.

Example:
```jsx
<Button gradient startColor="#a18cd1" endColor="#fbc2bc">
  <Text>Login</Text>
</Button>
```

**Comment by mohanyadav** [comment]
@hetmann Enjoying your modular code approach 👍 Please close this issue
