### ISSUE TITLE
Parking Finder App issue

### ISSUE THREAD

**Issue by Jorjill** [react-ui-kit/dribbble2react#37]
Hey, thanks for sharing this project. I found out that in the parking finder app information tab is not changing when I select different parking spots.

**Comment by hetmann** [comment]
@Snowarp thanks for noticing this one. Please check this commit:
https://github.com/react-ui-kit/dribbble2react/commit/fec603909a0eb67772419273d2bb1ae89df0ce3e

What I have done is:
1. use **ScrollView** instead of **FlatList**
2. create a ref for ScrollView
```jsx
parkingRef = React.createRef();
```
3. rendered all parking details
```jsx
parkings.map(item => this.renderParking(item))
```
4. onPress the Marker, scrolled to **width multiplied by Marker index**
```jsx
this.parkingRef.current.scrollTo({
  x: width * index
});
```
